[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

; Cấu hình USB CDC & PSRAM
build_flags = 
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D BOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue

; Khai báo mode PSRAM (Thử OPI trước)
board_build.arduino.memory_type = qio_opi
board_build.f_flash = 80000000L
board_build.flash_mode = qio

lib_deps = 
    links2004/WebSockets@^2.4.1
    bblanchon/ArduinoJson@^6.21.3